apiVersion: elbv2.k8s.aws/v2beta1
kind: TargetGroupBinding
metadata:
  name: frontend 
spec:
  serviceRef:
    name: frontend
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:361769572747:targetgroup/expense-dev/90b2094ce4e296b9